# Fluid 主题主配置（已合并官方最新示例 + 站点自定义）
# 官方文档: https://hexo.fluid-dev.com/docs/guide/
# 本文件在原有基础上补充：
# - fun_features / dark_mode / lazyload / font / open_graph 等官方段落
# - 统一使用 post.comments + comments 插件配置方式
# - 自定义 Waline 通过 custom_js 注入（保留 waline 插件配置以便未来升级主题时可直接生效）
# - 保留原有配色与导航、Banner、自定义 slogan

# 用于浏览器标签的图标
favicon: https://cdn.yangyus8.top/blog/geneden.webp

# 用于苹果设备的图标
apple_touch_icon: https://cdn.yangyus8.top/blog/geneden.webp

# 站点导航栏
navbar:
  blog_title: "杨与S8的个人博客"
  logo:
    text: 杨与S8
  menu:
    - name: 首页
      link: /
    - name: 归档
      link: /archives/
    - name: 分类
      link: /categories/
    - name: 标签
      link: /tags/
    - name: 关于
      link: /about/

# 主页 Banner
index:
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  slogan:
    enable: true
    text: 探索，实践，记录，分享

# 页脚
footer:
  content: '©<%= new Date().getFullYear() %> 杨与S8 <%- partial("_includes/build_revision") %>'
  beian:
    enable: false

# 代码块增强配置（基于官方最新字段 + 站点自定义主题）
code:
  copy_btn: true               # 显示复制按钮
  language:                    # 显示语言标识
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    line_number: true          # 行号
    lib: "highlightjs"         # 使用 highlight.js（已移除 Prism）
    highlightjs:
      style: "atom-one-light"  # 浅色主题
      style_dark: "atom-one-dark" # 深色主题

# 一些好玩的功能
fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
    scope: []
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left
    visible: hover
    icon: ""
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options: { showSpinner: false, trickleSpeed: 100 }

# 暗色模式（保持 auto, 支持 prefers-color-scheme）
dark_mode:
  enable: true
  default: auto

# 字体配置（官方段落，可按需再调整）
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

# 搜索（采用官方格式；本地生成 local-search.xml）
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

# RSS 订阅地址（自定义字段；避免与友链页面 links 配置冲突）
rss_feed: /atom.xml

# 文章页设置（整合官方结构 + 保留原有需求）
post:
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 70
  banner_mask_alpha: 0.3
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "LL a"
    wordcount:
      enable: true
    min2read:            # 用官方字段取代 readingtime
      enable: true
      awl: 2
      wpm: 60
    views:
      enable: false
      source: "busuanzi"
  updated:
    enable: false
    date_format: "LL a"
    relative: false
    note_class: info
  category_bar:
    enable: true
    specific: true
    placement: left
    post_order_by: "title"
    post_limit: 0
  toc:
    enable: true
    placement: right
    headingSelector: 'h1,h2,h3'
    collapseDepth: 0
  copyright:
    enable: true
    license: 'BY'
    author:
      enable: true
    post_date:
      enable: true
      format: "LL"
    update_date:
      enable: false
      format: "LL"
  prev_next:
    enable: true
  image_caption:
    enable: true
  image_zoom:
    enable: true
    img_url_replace: ['', '']
  footnote:
    enable: true
    header: ''
  math:
    enable: false
    specific: false
    engine: mathjax
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  comments:
    enable: true
    type: twikoo  # 切换为 Twikoo

# （已移除 prism 配置，统一使用 highlight.js）

# 自定义资源注入
# 注意：为确保 Waline v3 初始化，必须包含 /js/waline-init.js
custom_js: []
custom_css: []

# （删除旧 comment: 段，使用官方 post.comments + waline 插件配置）

# Waline (已停用，保留做回退参考)
# waline:
#   serverURL: https://blog.yangyus8.top/comment/
#   path: window.location.pathname
#   meta: ['nick', 'mail', 'link']
#   requiredMeta: ['nick']
#   lang: 'zh-CN'
#   emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
#   dark: 'html[data-user-color-scheme="dark"]'
#   wordLimit: 0
#   pageSize: 10

# Twikoo 配置（选择其一部署方式：腾讯云 CloudBase / Vercel / 自托管）
# 如果使用 Vercel / 自托管 API，把 envId 改成服务端地址，例如：https://comment.example.com
twikoo:
  envId: https://blog.yangyus8.top/twikoo/   # 自托管：使用 Nginx 反向代理前缀
  # region: ap-shanghai                      # 仅 CloudBase 需要，现自托管注释
  path: window.location.pathname
  # 可选高级参数（按需解注）：
  # lang: zh-CN
  # reaction: true
  # katex: false
  # uploadImage: true

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  # body_bg_color: "#eee"
  body_bg_color: "#f8f7f7"  # 比主色调更浅的暖灰
  # 暗色模式下的 body 背景色，下同
  # body_bg_color_dark: "#181c27"
  body_bg_color_dark: "#2a2828" # 比主色调稍深的灰

  # 顶部菜单背景色
  # navbar_bg_color: "#2f4154"
  # navbar_bg_color_dark: "#1f3144"
  navbar_bg_color: "#5a5555"  # 中性深灰 (主色调加深)
  navbar_bg_color_dark: "#1e1c1c" # 接近黑色的深灰

  # 顶部菜单字体色
  # navbar_text_color: "#fff"
  # navbar_text_color_dark: "#d0d0d0"
  navbar_text_color: "#f0eeee" # 柔和的米白
  navbar_text_color_dark: "#e3dede" # 直接使用亮色主色调

  # 副标题字体色
  # subtitle_color: "#fff"
  # subtitle_color_dark: "#d0d0d0"
  subtitle_color: "#c7c3c3" # 比正文深
  subtitle_color_dark: "#c7c3c3" # 比正文浅

  # 全局字体色
  # text_color: "#3c4858"
  # text_color_dark: "#c4c6c9"
  text_color: "#3a3636"  # 深炭灰
  text_color_dark: "#d9d5d5" # 浅灰 (比主色调亮20%)

  # 全局次级字体色（摘要、简介等位置）
  # sec_text_color: "#718096"
  # sec_text_color_dark: "#a7a9ad"
  sec_text_color: "#6b6666"  # 中灰
  sec_text_color_dark: "#9c9898" # 中浅灰

  # 主面板背景色
  # board_color: "#fff"
  # board_color_dark: "#252d38"
  board_color: "#ffffff"  # 纯白提升可读性
  board_color_dark: "#353232" # 比背景亮15%的灰

  # 文章正文字体色
  # post_text_color: "#2c3e50"
  # post_text_color_dark: "#c4c6c9"
  post_text_color: "#373434" # 比全局文字稍浅
  post_text_color_dark: "#d0cccc"

  # 文章正文字体色（h1 h2 h3...）
  # post_heading_color: "#1a202c"
  # post_heading_color_dark: "#c4c6c9"
  post_heading_color: "#262323" # 接近黑色
  post_heading_color_dark: "#f5f2f2" # 柔和白

  # 文章超链接字体色
  # post_link_color: "#0366d6"
  # post_link_color_dark: "#1589e9"
  post_link_color: "#7a6c6c"  # 灰紫调 (与主色协调)
  post_link_color_dark: "#a89d9d" # 浅灰紫

  # 超链接悬浮时字体色
  # link_hover_color: "#30a9de"
  # link_hover_color_dark: "#30a9de"
  link_hover_color: "#9b8d8d"  # 加深的灰紫
  link_hover_color_dark: "#c9c0c0"

  # 超链接悬浮背景色
  # link_hover_bg_color: "#f8f9fa"
  # link_hover_bg_color_dark: "#364151"
  link_hover_bg_color: "#f0eded" # 主色调10%淡化
  link_hover_bg_color_dark: "#423f3f"

  # 分隔线和表格边线的颜色
  # line_color: "#eaecef"
  # line_color_dark: "#435266"
  line_color: "#e0dcdc" # 主色调微调
  line_color_dark: "#4a4646"

  # 滚动条颜色
  # scrollbar_color: "#c4c6c9"
  # scrollbar_color_dark: "#687582"
  scrollbar_color: "#c4bcbc"
  scrollbar_color_dark: "#5d5858"
  # 滚动条悬浮颜色
  # scrollbar_hover_color: "#a6a6a6"
  # scrollbar_hover_color_dark: "#9da8b3"
  scrollbar_hover_color: "#a8a1a1"
  scrollbar_hover_color_dark: "#756f6f"

  # 按钮背景色
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"

  # 按钮悬浮背景色
  # button_hover_bg_color: "#f2f3f5"
  # button_hover_bg_color_dark: "#46647e"
  button_hover_bg_color: "#eeebeb" # 主色调5%淡化
  button_hover_bg_color_dark: "#454141"

# 图片与评论懒加载
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

# 网站访问统计（保持关闭，仅模板化保留）
web_analytics:
  enable: false
  follow_dnt: true
  baidu:
  google:
    measurement_id:
  tencent:
    sid:
    cid:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false
  umami:
    src:
    website_id:
    domains:
    start_time: 2024-01-01
    token:
    api_server:

# Open Graph
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# 归档 / 分类 / 标签 / 关于 / 友链 / 404 等页面（如需定制可继续扩展）
archive:
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 60
  banner_mask_alpha: 0.3
category:
  enable: true
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 60
  banner_mask_alpha: 0.3
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10
tag:
  enable: true
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"
about:
  enable: true
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "杨与S8"
  intro: "探索 · 实践 · 记录 · 分享"
links:
  enable: true
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 60
  banner_mask_alpha: 0.3
  items: []
page404:
  enable: true
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000
