# Fluid 主题主配置
# 文档: https://hexo-fluid.github.io/docs/

# 用于浏览器标签的图标
favicon: https://cdn.yangyus8.top/blog/geneden.webp

# 用于苹果设备的图标
apple_touch_icon: https://cdn.yangyus8.top/blog/geneden.webp

# 站点导航栏
navbar:
  blog_title: "杨与S8的个人博客"
  logo:
    text: 杨与S8
  menu:
    - name: 首页
      link: /
    - name: 归档
      link: /archives/
    - name: 分类
      link: /categories/
    - name: 标签
      link: /tags/
    - name: 关于
      link: /about/

# 主页 Banner
index:
  banner_img: https://cdn.yangyus8.top/blog/20250928.webp
  slogan:
    enable: true
    text: 探索，实践，记录，分享

# 页脚
footer:
  content: '©<%= new Date().getFullYear() %> 杨与S8 <%- partial("_includes/build_revision") %>'
  beian:
    enable: false

# 代码高亮（使用 hexo-prism-plugin 已预处理）
code:
  copy_btn: true
  highlight:
    enable: true    # 启用主题 / Hexo 内置 highlight.js 方案
    lib: "highlightjs"
    highlightjs:
      # 在官方 demo (https://highlightjs.org/demo/) 里挑选存在的文件名；Fluid 打包/或 CDN 可能不含 base16 子目录形式命名
      # 使用通用、稳定可用的样式，避免报 ‘not found’
      style: "atom-one-light"
      style_dark: "atom-one-dark"

# 本地搜索
search:
  enable: true
  type: local

# RSS 链接（Feed 插件生成的 atom.xml）
links:
  rss: /atom.xml

# 文章设置
post:
  meta:
    date: true
    category: true
    tag: true
    wordcount: true
    readingtime: true
  toc:
    enable: true
    headingSelector: 'h1,h2,h3'
    collapse: false
  comments:
    enable: true
    type: waline

# Prism 主题可自定义（可选）
prism: false  # 关闭 prism 自定义（迁移到内置 highlight）

# 自定义注入（按需）
custom_js: []
custom_css: []

# Waline 前端挂载点（在主题 layout 中已有 hooks，可用 injector 或直接在文章末尾 script 初始化——这里仅配置占位说明）
comment:
  enable: true
  type: waline
  # v3 客户端资源（ESM）
  js: https://unpkg.com/@waline/client@v3/dist/waline.js
  css: https://unpkg.com/@waline/client@v3/dist/waline.css

# Waline
# 从 Valine 衍生而来，额外增加了服务端和多种功能
# See: https://waline.js.org/
waline:
  serverURL: https://blog.yangyus8.top/comment/
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  # body_bg_color: "#eee"
  body_bg_color: "#f8f7f7"  # 比主色调更浅的暖灰
  # 暗色模式下的 body 背景色，下同
  # body_bg_color_dark: "#181c27"
  body_bg_color_dark: "#2a2828" # 比主色调稍深的灰

  # 顶部菜单背景色
  # navbar_bg_color: "#2f4154"
  # navbar_bg_color_dark: "#1f3144"
  navbar_bg_color: "#5a5555"  # 中性深灰 (主色调加深)
  navbar_bg_color_dark: "#1e1c1c" # 接近黑色的深灰

  # 顶部菜单字体色
  # navbar_text_color: "#fff"
  # navbar_text_color_dark: "#d0d0d0"
  navbar_text_color: "#f0eeee" # 柔和的米白
  navbar_text_color_dark: "#e3dede" # 直接使用亮色主色调

  # 副标题字体色
  # subtitle_color: "#fff"
  # subtitle_color_dark: "#d0d0d0"
  subtitle_color: "#c7c3c3" # 比正文深
  subtitle_color_dark: "#c7c3c3" # 比正文浅

  # 全局字体色
  # text_color: "#3c4858"
  # text_color_dark: "#c4c6c9"
  text_color: "#3a3636"  # 深炭灰
  text_color_dark: "#d9d5d5" # 浅灰 (比主色调亮20%)

  # 全局次级字体色（摘要、简介等位置）
  # sec_text_color: "#718096"
  # sec_text_color_dark: "#a7a9ad"
  sec_text_color: "#6b6666"  # 中灰
  sec_text_color_dark: "#9c9898" # 中浅灰

  # 主面板背景色
  # board_color: "#fff"
  # board_color_dark: "#252d38"
  board_color: "#ffffff"  # 纯白提升可读性
  board_color_dark: "#353232" # 比背景亮15%的灰

  # 文章正文字体色
  # post_text_color: "#2c3e50"
  # post_text_color_dark: "#c4c6c9"
  post_text_color: "#373434" # 比全局文字稍浅
  post_text_color_dark: "#d0cccc"

  # 文章正文字体色（h1 h2 h3...）
  # post_heading_color: "#1a202c"
  # post_heading_color_dark: "#c4c6c9"
  post_heading_color: "#262323" # 接近黑色
  post_heading_color_dark: "#f5f2f2" # 柔和白

  # 文章超链接字体色
  # post_link_color: "#0366d6"
  # post_link_color_dark: "#1589e9"
  post_link_color: "#7a6c6c"  # 灰紫调 (与主色协调)
  post_link_color_dark: "#a89d9d" # 浅灰紫

  # 超链接悬浮时字体色
  # link_hover_color: "#30a9de"
  # link_hover_color_dark: "#30a9de"
  link_hover_color: "#9b8d8d"  # 加深的灰紫
  link_hover_color_dark: "#c9c0c0"

  # 超链接悬浮背景色
  # link_hover_bg_color: "#f8f9fa"
  # link_hover_bg_color_dark: "#364151"
  link_hover_bg_color: "#f0eded" # 主色调10%淡化
  link_hover_bg_color_dark: "#423f3f"

  # 分隔线和表格边线的颜色
  # line_color: "#eaecef"
  # line_color_dark: "#435266"
  line_color: "#e0dcdc" # 主色调微调
  line_color_dark: "#4a4646"

  # 滚动条颜色
  # scrollbar_color: "#c4c6c9"
  # scrollbar_color_dark: "#687582"
  scrollbar_color: "#c4bcbc"
  scrollbar_color_dark: "#5d5858"
  # 滚动条悬浮颜色
  # scrollbar_hover_color: "#a6a6a6"
  # scrollbar_hover_color_dark: "#9da8b3"
  scrollbar_hover_color: "#a8a1a1"
  scrollbar_hover_color_dark: "#756f6f"

  # 按钮背景色
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"

  # 按钮悬浮背景色
  # button_hover_bg_color: "#f2f3f5"
  # button_hover_bg_color_dark: "#46647e"
  button_hover_bg_color: "#eeebeb" # 主色调5%淡化
  button_hover_bg_color_dark: "#454141"